version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: ap-northeast-1
    REPOSITORY_NAME: codebuild-docker-rate-limit-verification
  parameter-store:
    DOCKER_HUB_ID: /CodeBuild/DOCKER_HUB_ID
    DOCKER_HUB_PASSWORD: /CodeBuild/DOCKER_HUB_PASSWORD
    REPOSITORY_URI: /CodeBuild/REPOSITORY_URI

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ${AWS_DEFAULT_REGION} | docker login --username AWS --password-stdin ${REPOSITORY_URI}
      - echo Logging in to Docker Hub...
      - echo ${DOCKER_HUB_PASSWORD} | docker login -u ${DOCKER_HUB_ID} --password-stdin
      - echo Pulling latest docker image...
      - docker pull ${REPOSITORY_URI}/${REPOSITORY_NAME}:latest
  build:
    commands:
      - echo Docker build and push to Amazon ECR...
      - docker build --cache-from ${REPOSITORY_URI}/${REPOSITORY_NAME}:latest -t ${REPOSITORY_NAME} .
      - docker tag ${REPOSITORY_NAME}:latest ${REPOSITORY_URI}/${REPOSITORY_NAME}:latest
      - docker push ${REPOSITORY_URI}/${REPOSITORY_NAME}:latest
